import asyncio
import time
from .base import ILlmProvider, CompletionRequest, CompletionResponse

_MOCK_RESPONSES: list[tuple[list[str], str]] = [
    (
        ["concise summary", "summarise", "summarize", "key components", "overview of"],
        "This repository implements a layered enterprise application following Clean Architecture principles. "
        "It is built on .NET 8 and consists of a Web API backend, an ASP.NET MVC frontend, FastAPI AI services, "
        "and supporting libraries for core domain logic, infrastructure, and shared contracts. The solution "
        "demonstrates separation of concerns, dependency injection, and enterprise coding standards.",
    ),
    (
        ["architectural layers", "architectural patterns", "n-tier", "how is it structured", "analyse the"],
        "The architecture follows a classic n-tier pattern with clear separation between presentation, "
        "business logic, and data access layers. Controllers handle HTTP concerns, services encapsulate "
        "business rules, and repositories abstract data persistence. External dependencies are injected "
        "through interfaces, making the system highly testable and maintainable.",
    ),
    (
        ["explain what", "how does", "repository pattern", "what does this code", "explain the purpose"],
        "This code implements the repository pattern to abstract data access from business logic. "
        "The class follows SOLID principles — it has a single responsibility, depends on abstractions "
        "rather than concrete implementations, and is open for extension without modification. "
        "Dependency injection is used throughout for testability.",
    ),
    (
        ["potential impact", "affected components", "component_name", "dependencies", "risk"],
        "Changing this component has a moderate-to-high impact across the system. "
        "Direct consumers include service classes and API controllers that depend on this interface. "
        "Indirect effects propagate to integration tests and dependent modules. "
        "Recommended: update all callers, run integration tests, and review dependency injection registrations.",
    ),
    (
        ["synthesize", "combine", "based on the analysis", "provide a clear"],
        "Based on the analysis performed, this enterprise codebase follows Clean Architecture principles "
        "with clear separation between presentation, business logic, and data access layers. "
        "The system is built on .NET 8, uses ASP.NET Core MVC for the frontend, Web API for the backend, "
        "and FastAPI for AI services. Key strengths include strong dependency injection, "
        "interface-driven design, and a well-structured multi-project solution.",
    ),
]

_DEFAULT_RESPONSE = (
    "This is a mock AI response generated by the ECIP Mock LLM provider. "
    "No actual language model was invoked. Switch to OpenAI, Gemini, or Ollama "
    "in the AI Settings page to use a real language model."
)


class MockLlmProvider(ILlmProvider):
    def __init__(self, delay_ms: int = 500):
        self._delay_ms = delay_ms

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return "mock-llm-v1"

    async def complete(self, request: CompletionRequest) -> CompletionResponse:
        start = time.monotonic()

        if self._delay_ms > 0:
            await asyncio.sleep(self._delay_ms / 1000)

        prompt_lower = request.prompt.lower()
        content = _DEFAULT_RESPONSE
        for keywords, response in _MOCK_RESPONSES:
            if any(kw in prompt_lower for kw in keywords):
                content = response
                break

        duration_ms = int((time.monotonic() - start) * 1000)
        return CompletionResponse(
            content=content,
            provider=self.provider_name,
            model=self.model_name,
            input_tokens=len(request.prompt.split()),
            output_tokens=len(content.split()),
            duration_ms=duration_ms,
        )
