import asyncio
import time
from .base import ILlmProvider, CompletionRequest, CompletionResponse

_MOCK_RESPONSES: dict[str, str] = {
    "summarize_repository": (
        "This repository implements a layered enterprise application following Clean Architecture principles. "
        "It is built on .NET 8 and consists of a Web API backend, an ASP.NET MVC frontend, and supporting "
        "libraries for core domain logic, infrastructure, and shared contracts. The solution demonstrates "
        "separation of concerns, dependency injection, and enterprise coding standards."
    ),
    "analyze_architecture": (
        "The architecture follows a classic n-tier pattern with clear separation between presentation, "
        "business logic, and data access layers. Controllers handle HTTP concerns, services encapsulate "
        "business rules, and repositories abstract data persistence. External dependencies are injected "
        "through interfaces, making the system highly testable and maintainable."
    ),
    "explain_code": (
        "This code implements the repository pattern to abstract data access from business logic. "
        "The class follows SOLID principles — it has a single responsibility, depends on abstractions "
        "rather than concrete implementations, and is open for extension without modification. "
        "Dependency injection is used throughout for testability."
    ),
    "default": (
        "This is a mock AI response generated by the ECIP Mock LLM provider. "
        "No actual language model was invoked. Switch to OpenAI, Gemini, or Ollama "
        "in the AI Settings page to use a real language model."
    ),
}


class MockLlmProvider(ILlmProvider):
    def __init__(self, delay_ms: int = 500):
        self._delay_ms = delay_ms

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return "mock-llm-v1"

    async def complete(self, request: CompletionRequest) -> CompletionResponse:
        start = time.monotonic()

        if self._delay_ms > 0:
            await asyncio.sleep(self._delay_ms / 1000)

        prompt_lower = request.prompt.lower()
        content = _MOCK_RESPONSES["default"]
        for key, response in _MOCK_RESPONSES.items():
            if key != "default" and key in prompt_lower:
                content = response
                break

        duration_ms = int((time.monotonic() - start) * 1000)
        return CompletionResponse(
            content=content,
            provider=self.provider_name,
            model=self.model_name,
            input_tokens=len(request.prompt.split()),
            output_tokens=len(content.split()),
            duration_ms=duration_ms,
        )
